school_App/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
 	url(r'^schools/', include('schools.urls')),
    url(r'^admin/', admin.site.urls),
]

schools/urls.py
from django.conf.urls import url
from . import views
app_name ='schools'
urlpatterns = [
	#/schools/
    url(r'^$', views.home, name= 'home'),
    url(r'^home/$', views.home, name= 'home'),
    url(r'^login/$', views.login, name= 'login'),
    url(r'^registration/$', views.registration, name= 'registration'),
    url(r'^about/$', views.about, name= 'about'),
    url(r'^school_sub/$', views.school_sub, name= 'school_sub'),
    url(r'^regForm/$',views.regForm, name = 'regForm'),
    url(r'^showSchoolsList/$',views.showSchoolsList, name = 'showSchoolsList'),
    url(r'^validateLogin/$', views.validateLogin, name = 'validateLogin'),
    url(r'^loadArea/$', views.loadArea, name='loadArea'),
]

schools/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
# Create your models here.
class UserInfo(models.Model):
	GENDER_CHOICES = (
        ('F', 'Female'),
        ('M', 'Male'),
    )
	FirstName = models.CharField(max_length = 250, default='name')
	LastName = models.CharField(max_length = 250)
	# Dob = models.DateField(blank=True, null=True,default=datetime.date.today)
	Email = models.CharField(max_length = 250)
	PhoneNumber = models.IntegerField()
	Password = models.CharField(max_length = 250)
	Gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
	City = models.CharField(max_length = 250)
	ZipCode = models.CharField(max_length = 250)
	Country = models.CharField(max_length = 250)
	Address = models.CharField(max_length = 1000)

	def __str__(self):
		return self.FirstName + ' - ' + self.LastName

class City(models.Model):
	city_Name = models.CharField(max_length = 250)

	def __str__(self):
		return self.city_Name

class Area(models.Model):
	city = models.ForeignKey(City,on_delete = models.CASCADE)
	city_areas = models.CharField(max_length = 250)

	def __str__(self):
		return self.city_areas  + ' - ' + self.city.city_Name

class Schools(models.Model):
	area = models.ForeignKey(Area,on_delete = models.CASCADE)
	school_Name = models.CharField(max_length = 250, default='name')
	school_Img = models.CharField(max_length = 250)
	school_distance = models.IntegerField()
	school_address = models.CharField(max_length = 1000)
	school_desc = models.CharField(max_length = 1500)
	school_Location = models.CharField(max_length = 1000)
	school_contact = models.CharField(max_length = 1000)
	school_Email = models.CharField(max_length = 250)
	school_WebAddress = models.CharField(max_length = 250)

	def __str__(self):
		return self.school_Name  + ' - ' + self.area.city_areas + ' - ' + self.area.city.city_Name

schools/forms.py
from django import forms
from django.conf import settings
# class RegstrationForm(forms.Form):
# 	GENDER_CHOICES = (
#         ('F', 'Female'),
#         ('M', 'Male'),
#     )
# 	FirstName = forms.CharField()
# 	LastName = forms.CharField()
# 	Email = forms.EmailField()
# 	PhoneNumber = forms.IntegerField()
# 	Password = forms.CharField()
# 	Dob = forms.DateField(input_formats = settings.DATE_INPUT_FORMATS)
# 	Gender = forms.ChoiceField(widget = forms.RadioSelect(), choices=GENDER_CHOICES)
# 	City = forms.CharField()
# 	ZipCode = forms.CharField()
# 	Country = forms.CharField()
# 	Address = forms.CharField()


class MapForm(forms.Form):
    Address = forms.CharField(label='Address', max_length=100)

schools/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.http import HttpResponse
from .forms import MapForm
from .models import UserInfo , City, Area,Schools

# Create your views here.
def home(request):
	cities = City.objects.all()	
	areas = Area.objects.all()

	context = {
	'cities':cities,
	# 'areas' : areas
	}
	return render(request,'schools/home.html',{'context':context})

def login(request):
	return render(request,'schools/login.html',{'context':'this is login'})

def registration(request):
	return render(request,'schools/registration.html',{'context':'this is login'})
def about(request):
	return render(request,'schools/about.html',{'context':'this is about'})
def regForm(request):
	# form  = RegstrationForm()
	FirstName = request.POST.get('FirstName','')
	LastName = request.POST.get('LastName','')
	Email = request.POST.get('Email','')
	PhoneNumber = request.POST.get('PhoneNumber','')
	Password = request.POST.get('Password','')
	# Dob = request.POST.get('Dob','')
	Gender = request.POST.get('Gender','')
	City = request.POST.get('City','')
	ZipCode = request.POST.get('ZipCode','')
	Country = request.POST.get('Country','')
	Address = request.POST.get('Address','')
	user = UserInfo(FirstName = FirstName, LastName = LastName, Email = Email , PhoneNumber = PhoneNumber ,Password= Password ,Gender =Gender, City =City,  ZipCode = ZipCode, Country = Country, Address =Address)
	user.save()

	return render(request,'schools/home.html',{'context':'this is home'})

def showSchoolsList(request):
	city_id = request.POST.get('city','')
	area_id = request.POST.get('area','')
	
	schoolsList = Schools.objects.filter(area__city__pk =city_id, area__pk = area_id)
	print(schoolsList)
	return render(request,'schools/schoolList.html',{'schoolsList':schoolsList})
	
def validateLogin(request):
	FirstName = request.POST.get('userName','')
	Password = request.POST.get('Password','')

	if UserInfo.objects.filter(FirstName = FirstName ,Password = Password).exists():
		
		return render(request,'schools/home.html',{'context':'valid user'})
	else :
		
		return render(request,'schools/login.html',{'context':'invalid'})

def loadArea(request):
	city_id = request.GET.get('cityId')

	city = City()
	areas = Area.objects.filter(city__pk = city_id)
	print(areas)
	return render(request,'schools/home.html',{'areas':areas})
	# return render(request, 'schools/loadAreas.html',  {'areas': areas})

def school_sub(request):
	if request.method == 'POST':
		Address = request.POST.get('Address','')
		
	else:
		Address = 'hyderabad'

	context = { 'name': Address }
	print(context)	
	return render(request, 'schools/school_sub.html',  {'context':context})


schools/templates/schools/base.html
<html>
	
	<head>	
		<title> School App</title>
		{% load staticfiles %}


		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
	    <meta name="viewport" content="width=device-width, initial-scale = 1.0,
				maximum-scale=1.0, user-scalable=no" />
	    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	    <title>School-App</title>
	    <!-- Bootstrap -->

	    <link  href = "{%static 'schoolList/css/bootstrap.min.css' %}" rel="stylesheet">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css" />
	    <link href = "{%static 'schoolList/css/style.css' %}" rel="stylesheet" />
	    <!-- <link href = "{%static 'schoolList/css/font-awesome.min.css' %}" rel="stylesheet" /> -->
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700" rel="stylesheet">

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	    <![endif]-->
	    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->

	    <!--Bower components -->

	    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>

	    <!-- <script src="http://maps.google.com/maps/api/js?key=AIzaSyDewl8haI70rBJLQe3ZjjQ_qfYZMljgUa4&libraries=places"></script> -->
	    <script data-require="lodash-underscore@*" data-semver="2.4.1" src="https://rawgit.com/lodash/lodash/2.4.1/dist/lodash.underscore.min.js"></script>
	    <script data-require="angular-google-maps@*" data-semver="1.1.4" src="https://rawgit.com/nlaplante/angular-google-maps/1.1.4/dist/angular-google-maps.min.js"></script>

	     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	   <!--  <script src="{%static 'schoolList/bower_components/angular-route/angular-route.js' %}"></script>
	    <script src="{%static 'schoolList/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js' %}"></script> -->
	    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
	</head>

	<body>
		 <header>
        <div class="container" ng-controller="mainctrl">
            <div class="row">
                <div class="top-header col-md-12">
                    <div class="left-help col-md-6  col-xs-5 col-sm-6">
                        <a href="#!help"><i class="fa fa-question-circle-o"></i>Help</a>
                    </div>
                    <div class="right-login col-md-6 col-xs-7  col-sm-6">
                        <ul>
                            <li ng-hide="isLoggedIn"><a href="{% url 'schools:login' %}" ><i class="fa fa-user-circle-o"></i>Login</a></li>
                            <li ng-hide="isLoggedIn">or</li>
                            <li ng-hide="isLoggedIn"><a href="{% url 'schools:registration' %}">Sign up</a></li>                          
                            <li ng-show="isLoggedIn" ng-click="logOut()"><i class="fa fa-user-circle-o"></i> Log Out</li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </header>

		{% block body %}
		{% endblock %}

		  <footer>
        <div class="container">
            <div class="row">
                <div class="bottom-footer">
                    <div class="Copyright col-md-6  col-xs-5 col-sm-6">
                        <p>&#169; Copyright 2017.</p>
                    </div>
                    <div class="media-icons col-md-6  col-xs-7  col-sm-6">
                        <ul>
                            <li><a href="https://www.facebook.com/"><i class="fa fa-facebook-square"></i></a></li>
                            <li><a href="https://twitter.com/"><i class="fa fa-twitter-square"></i></a></li>
                            <li><a href="https://www.linkedin.com/"><i class="fa fa-linkedin-square"></i></a></li>
                            <li><a href="https://www.youtube.com/"><i class="fa fa-youtube-square"></i></a></li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </footer>
	</body>

</html>


schools/templates/schools/home.html
{% extends 'schools/base.html' %}

{% block body %}
{% load staticfiles%}
	<div class="page-wrapper" id = 'home'>
		<section>
        	<div class="row">
           		<div id="chooseService" class="col-md-12 banner">
           			
           			<img src="{% static 'schoolList/images/banner_bg.jpg'%}" alt="My image"/>
              		<div class="content">
	                    <h1>Choose the right way</h1>
	                    <p>Education is most powerful weapon which you can use to change the world</p>
                	</div>

                	<div class="form-fields">
	                    <div class="select-form">
	                    	<form action = "{% url 'schools:showSchoolsList' %}" method = "post" id="cityForm" data-areas-url="{% url 'schools:loadArea' %}">  {% csrf_token%}
	                        <div class="select-box">
	                        	 
	                        	 	<select name="city" onchange="onChangeCity()" id = 'city'>
									{% for city in context.cities %}

									    <option value="{{ city.pk }}" selected="selected" name = 'city'>{{city.city_Name}}</option>	
					    	      	{% endfor %}
								</select>
	                        		
	                            
	                        </div>
	                        <div class="select-box">
	                            <!-- <select ng-options="x for x in selectedAreaName " ng-model="selectedArea" ng-change="selectAreaNames()"> </select> -->
	                            <select name="area" id = "area" >
							<!-- 	{% for area in context.areas %}		        
									    <option value="{{area.city_areas}}" selected="selected" name = 'area'>{{area.city_areas}}</option>	
					    	      	{% endfor %} -->
								</select>

	                        </div>
	                        <div class="select-box">
	                            <select>
	                                <option> Select service</option>
	                                <option>Schools</option>
	                                <option>Tutions</option>
	                            </select>

	                        </div>
	                        <div class="select-box">
	                            <!-- <button class="btn btn-default" ng-click="showSchoolsInfo()">submit</button> -->
	                            <input type = 'submit' value = submit>
	                        </div>
	                        </form>
	                    </div>
                	</div>
            	</div>
        	</div>
   	    </section>

   	    <section>
        <div class="col-md-12">
            <div class="aboutUs container">
                <h3>ABOUT US</h3>           
                <div class="pp"></div>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                <div class="btn-about"><a href= "{% url 'schools:about' %}">View More <i class="fa fa-long-arrow-right"></i></a></div>
                <div class="clearfix"></div>
            </div>
        </div>
    </section>
	</div>


	 <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    function onChangeCity() {
      
		var cityId = document.getElementById("city").value;
		var url = $("#cityForm").attr("data-areas-url");
		 $.ajax({   url: url,
					 data: {
					          'cityId': cityId       // add the country id to the GET parameters
					        },
				       success: function (data) {   // `data` is the return of the `load_areas` view function
				       	 console.log(data)
		           $("#area").html(data);  // replace the contents of the city input with the data that came from the server
		        }
		      });
				 }
  </script>
{% endblock %}

<!-- function onChangeCity(){
    new Ajax.Request('/auto/ajax_color_request/', { 
    method: 'post',
    parameters: $H({'type':$('id_type').getValue()}),
    onSuccess: function(transport) {
        var e = $('id_color')
        if(transport.responseText)
            e.update(transport.responseText)
    }
    }); // end new Ajax.Request
} -->

schools/templates/schools/loadAreas.html

{% for area in areas %}
<option value="{{area.pk}}" selected="selected" name = 'area'>{{area.city_areas}}</option>	
{% endfor %}

schools/templates/schools/login.html
{% extends 'schools/base.html' %}

{% block body %}
	{% load staticfiles%}
	<div class="page-wrapper">
    <section>
        <div class="container-fluid">
            <div class="row">
            	
                <div class="banner inner-page" id="inner-page">
                    <img src="{% static 'schoolList/images/inner-page-banner.jpg'%}" />

                    <div class="caption">
                        <h2><span class="sub-title">EDUCATION</span> IS THE MOST POWERFUL WEAPON <br>WHICH YOU CAN USE TO CHANGE <br> THE <span>WORLD.</span></h2>
                        <cite>Nelson Mandela</cite>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="login" ng-controller="loginController">
            <div class="container">
                <div class="row">
                    <div class="form">
                        <h3>LOGIN</h3>
                        <div class="form-fields">
                            <div class="login-fields">
                                <form  action = "{% url 'schools:validateLogin' %}" method = "post">
                                    {% csrf_token%}
                                    <input type="text" class="input-field " name="userName" placeholder="User name..."><br>
                                    <input type="password" class="input-field " name="Password" placeholder="password..."><br>
                                
                                    <button type = 'submit' class="btn btn-default" ng-click="validationLoginForm()">Log In</button>
                                
                                    <a href="{% url 'schools:registration' %}">
                                    <button class="btn btn-default" ng-click="toggleToReg()">Register</button><br></a>
                                </form>
                            </div>
                            <div class="message">{{message}}</div>

                            <button class="btn btn-primary btn-block" ng-click="forgotPwd()">Forgot Password?</button>

                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

schools/templates/schools/registration.html
{% extends 'schools/base.html' %}

{% block body %}
	{% load staticfiles%}
	<div class="page-wrapper">
    <section>
        <div class="row">
            <div class="banner inner-page">
               
                 <img src="{% static 'schoolList/images/inner-page-banner.jpg'%}" />
                    <div class="caption">
                <h2>the aim of<span class="sub-title">education</span> IS THE knowledge, <br>not of facts, but of values</h2>
                    <cite>william S.Burroughs</cite>
                     
            </div>          
            </div>  
            <div class="clearfix"></div>            
        </div>      
    </section>
    
    <section>
        <div class="reg-body" ng-controller="regController">
            <div class="container">
                <div class="row">
                    <div class="reg-form">
                        
                        <h3>REGISTRATION</h3>
                        <form action = "{% url 'schools:regForm' %}" method = "post">
                            {% csrf_token%}

                            <div class="form-group">
                                <label class="col-md-4 col-xs-4">First name</label>
                                <div class="col-md-8 col-xs-8">
                                <input type="text" placeholder="First name" class="form-control"  name = "FirstName" autofocus>

                                </div>
                            <div class="clearfix"></div>
                            </div>
                        <div class="form-group">
                                <label class="col-md-4 col-xs-4">last name</label>
                                <div class="col-md-8 col-xs-8">
                                <input type="text" placeholder="Full name" class="form-control"  name = 'LastName' autofocus>

                                </div>
                            <div class="clearfix"></div>
                            </div>
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4"><span>*</span>Email</label>
                                <div class="col-md-8 col-xs-8">
                                    <input type="text" placeholder="Email" class="form-control" name = 'Email' autofocus> 

                                </div>
                            <div class="clearfix"></div>
                        </div>

                          <div class="form-group">
                            <label class="col-md-4 col-xs-4"><span>*</span>Phone Number</label>
                                <div class="col-md-8 col-xs-8">
                                    <input type="text" placeholder="Phone Number" class="form-control" name="PhoneNumber" autofocus>

                                </div>
                            <div class="clearfix"></div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4">Password</label>
                                <div class="col-md-8 col-xs-8">
                                    <input type="password" placeholder="Password" class="form-control" name="Password" autofocus>

                                </div>
                            <div class="clearfix"></div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4">Date of Birth</label>
                                <div class="col-md-8 col-xs-8">
                                    <input type="date" placeholder="mm/dd/yyyy" class="form-control" name="date" name="Dob" fpattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" autofocus>

                                </div>
                            <div class="clearfix"></div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4">Gender</label>
                                <div class="col-md-8 col-xs-8 gender">
                                    
                                    <label class="radio-inline col-xs-8">
                                        <input name="radioGroup" id="radio1" value="M" checked="" type="radio" name="Gender">
                                        Male
                                    </label>
                                    <label class="radio-inline col-xs-8">
                                        <input name="radioGroup" id="radio2" value="F" type="radio" name="Gender">
                                        Female
                                    </label>
                                    
                                    
                                </div>
                                <div class="clearfix"></div>
                        </div>

                        <div class="form-group">
                                <label class="col-md-4 col-xs-4">City</label>
                                <div class="col-md-8 col-xs-8">
                                <input type="text" placeholder="City" class="form-control" name="City"autofocus>

                                </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4">Zip Code</label>
                                <div class="col-md-8 col-xs-8">
                                    <input type="text" placeholder="Zip Code" class="form-control" name="ZipCode"autofocus/>

                                </div>
                            <div class="clearfix"></div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 col-xs-4">Country</label>
                                <div class="col-md-8 col-xs-8 country">
                                    <select class="form-control" name ="Country">
                                        <option>Country</option>
                                        <option>India</option>
                                        <option>Sri Lanka</option>
                                    </select>
                                </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="form-group address">
                                <label class="col-md-4 col-xs-4">Address</label>
                                    <div class="col-md-8 col-xs-8">
                                        <textarea rows="8" cols="40"placeholder="Address" name="Address"></textarea>
                                    </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 col-xs-12">
                            <input type="checkbox" ng-model="terms"/> I agree with the term and conditions for registration<span>*</span>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="message" ng-style="myStyle">{{message}}</div>
                        <div class="form-group">
                        <label class="col-md-4 col-xs-4"></label>
                            <div class="col-md-8 col-xs-8">
                                <input type="submit" name="submit" value = "Submit"/>
                                <!-- <button type="button" class="btn btn-default submitbutn" ng-click="validationRegForm()">Submit</button> -->
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        </form>                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    
  </div> 



{% endblock %}

schools/templates/schools/schoolList.html

{% extends 'schools/base.html' %}

{% block body %}
{% load staticfiles%}

	<div ng-controller="schoolsController" class="page-wrapper">
    <section>
        <div class="row">
            <div class="banner inner-page">
                <img src="{% static 'schoolList/images/inner-page-banner.jpg'%}" alt="My image"/>
                <div class="caption">
                    <h2><span class="sub-title">education</span> is not preparation for life<br> <span>education</span>is life itself.</h2>
                    <cite>John Dewey</cite>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="schoolsearch">
            <div class="container">
                <ul class="breadcrump ">
                    <li> <a href="#!school">{{currentSelectedCity}}</a><span>/</span></li>
                    <li><a href="#!school">{{currentSelectedArea}}</a></li>
                </ul>

                <div class="searchbox  pull-right">
                    <input type="search" placeholder="search...." ng-model="schoolsInSelectedArea.schoolName"/>
                    <i class="fa fa-search" aria-hidden="true"></i>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </section>
    <section>
        <div class="near-schools">
            <div class="container">
                <div class="row">
                    
                    <div class="school-block col-md-4 col-xs-12 col-sm-6" ng-repeat="i in schoolsInSelectedArea |filter: schoolsInSelectedArea.schoolName ">

                    	{% for schl in schoolsList %}
        					<!-- <img src="{% static 'schoolList/images/block1.jpg'%}"  -->
        					<!-- <p class="distance">{{schl.school_distance}}</p> -->
        					<div class="school-address">
	                            <h3>{{schl.school_Name}}</h3>
	                            <p>{{schl.school_Location}}</p>
	                            <div class="clearfix"></div>
	                            <div class="viwe-more" ><a href="{% url 'schools:school_sub' %}">View More <i class="fa fa-long-arrow-right"></i></a></div>
                        		<div class="clearfix"></div>
                        	</div>
									   
						 {% endfor %}
                       <!--  <img src={{i.imgPath}} />
                        <p class="distance">{{i.distance}}</p>
                        <div class="school-address">
                            <h3>{{i.schoolName}}</h3>
                            <p>{{i.schoolLocation}}</p>
                            <div class="clearfix"></div>
                        </div>
                        <div class="viwe-more" ng-click="selectedSchool($index)"><a href="#!school_sub">View More <i class="fa fa-long-arrow-right"></i></a></div>
                        <div class="clearfix"></div> -->
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

schools/templates/schools/school_sub.html
<h1>Google Map</h1>
 
{% load easy_maps_tags %}

<!-- Default map with 300x400 dimensions -->
<!-- {% easy_map "Russia, Ekaterinburg, Mira 32" 300 400 %} -->
{% easy_map context.name 800 400 %}
<!-- {% easy_map object.map_location 350 200 %} -->

<form action="{% url 'schools:school_sub' %}" method="post">
    {% csrf_token %}
    
    <input type = 'text' name= 'Address'/>
    <input type="submit" value="Get Directions" />
</form>